# This is a very simple Knative Service that writes the input request to its log.

apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: my-keptn-service
  namespace: keptn
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        metadata:
          name: service-builder
          namespace: keptn
        spec:
          serviceAccountName: build-bot
          source:
            git:
              url: https://github.com/bacherfl/keptn-ref-service.git
              revision: master
          template:
            name: kaniko
            arguments:
              - name: IMAGE
                value: docker-registry.keptn.svc.cluster.local:5000/keptn/my-keptn-service:latest
      revisionTemplate:
        spec:
          container:
            image: REGISTRY_URI_PLACEHOLDER:5000/keptn/my-keptn-service:latest
            env:
              PROMETHEUS_URL: PROMETHEUS_URL_PLACEHOLDER
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: my-keptn-service-tests-finished-subscription
  namespace: keptn
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: tests-finished
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: my-keptn-service
